# Generated by Django 3.2 on 2021-05-31 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_contactmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textmodel',
            old_name='date_edit',
            new_name='date_edited',
        ),
    ]
