from .contact import contact
from .base import base
from .category import category
from .my_blogs import my_blogs
from .detail import detail
from .add_blog import add_blog
from .update_blog import update_blog
from .delete_blog import delete_blog
from .delete_comment import delete_comment
from .blogs import blogs
